apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Application
    patch: |
      - op: replace
        path: /spec/syncPolicy
        value:
          retry:
            limit: 10
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 10m
