apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Application
    patch: |
      - op: add
        path: /spec/syncPolicy/retry
        value:
          limit: 20
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 30m
