apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: system
  destination:
    namespace: cloud-controllers
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.13.1
    helm:
      releaseName: external-dns
      values: |
        provider: aws
        sources:
          - service
          - ingress
        policy: sync
        deploymentStrategy:
          type: Recreate
        txtOwnerId: external-dns-<path:/eks/cluster/main/details#name#AWSCURRENT>
        txtSuffix: ''
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: "<path:/eks/cluster/main/iam/roles#external_dns#AWSCURRENT>"
