apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=true
  name: bottlerocket-default
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 4Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      encrypted: true
      volumeSize: 20Gi
      volumeType: gp3
  instanceProfile: KarpenterNodeRole-main
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  securityGroupSelector:
    #aws-ids: <path:/eks/cluster/20231126/main/details#security_group#AWSCURRENT>
    aws:eks:cluster-name: <path:/eks/cluster/20231126/main/details#name#AWSCURRENT>
    #karpenter.sh/discovery: <path:/eks/cluster/20231126/main/details#name#AWSCURRENT>
    #kubernetes.io/cluster/<path:/eks/cluster/20231126/main/details#name#AWSCURRENT>: owned
  subnetSelector:
    karpenter.sh/discovery: <path:/eks/cluster/20231126/main/details#name#AWSCURRENT>
  userData: |-
    [settings.kubernetes.eviction-hard]
    "memory.available" = "12%"
    "nodefs.available" = "10%"
    "nodefs.inodesFree" = "5%"
    [settings.kubernetes.eviction-soft]
    "memory.available" = "15%"
    "nodefs.available" = "12%"
    "nodefs.inodesFree" = "8%"