apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devel
  destination:
    namespace: vcluster
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  source:
    chart: vcluster-eks
    repoURL: https://charts.loft.sh
    targetRevision: 0.19.5
    plugin:
      env:
        - name: HELM_VALUES
          value: |-
            embeddedEtcd:
              enabled: false
              migrateFromEtcd: false

            plugin: {}
