apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: monitoring
  destination:
    namespace: opensearch
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  source:
    chart: opensearch
    repoURL: https://opensearch-project.github.io/helm-charts
    targetRevision: 2.14.1
    helm:
      releaseName: opensearch
      values: |
        singleNode: false

        roles:
          - master
          - ingest
          - data
          - remote_cluster_client

        replicas: 3

        config:
          log4j2.properties: |-
            status = error

            appender.console.type = Console
            appender.console.name = console
            appender.console.layout.type = PatternLayout
            appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n

            rootLogger.level = info
            rootLogger.appenderRef.console.ref = console
          # https://github.com/opensearch-project/security/blob/main/config/opensearch.yml.example
          opensearch.yml: |-
            cluster.name: test
            network.host: 0.0.0.0
            plugins:
              security:
                disabled: true
                ssl:
                  transport:
                    pemcert_filepath: esnode.pem
                    pemkey_filepath: esnode-key.pem
                    pemtrustedcas_filepath: root-ca.pem
                    enforce_hostname_verification: false
                  http:
                    enabled: false
                    pemcert_filepath: esnode.pem
                    pemkey_filepath: esnode-key.pem
                    pemtrustedcas_filepath: root-ca.pem
                nodes_dn_dynamic_config_enabled: true
                nodes_dn:
                  - "CN=*.example.com, OU=node, O=node, L=test, C=de"
                allow_unsafe_democertificates: true
                allow_default_init_securityindex: true
                authcz:
                  admin_dn:
                    - CN=kirk,OU=client,O=client,L=test,C=de
                audit.type: internal_opensearch
                enable_snapshot_restore_privilege: true
                check_snapshot_restore_write_privileges: true
                restapi:
                  roles_enabled: ["all_access", "security_rest_api_access"]
                system_indices:
                  enabled: false
                  indices:
                    [
                      ".opendistro-alerting-config",
                      ".opendistro-alerting-alert*",
                      ".opendistro-anomaly-results*",
                      ".opendistro-anomaly-detector*",
                      ".opendistro-anomaly-checkpoints",
                      ".opendistro-anomaly-detection-state",
                      ".opendistro-reports-*",
                      ".opendistro-notifications-*",
                      ".opendistro-notebooks",
                      ".opendistro-asynchronous-search-response*",
                    ]

        opensearchJavaOpts: "-Xmx8192M -Xms8192M"

        resources:
          requests:
            cpu: 1000m
            memory: 2048Mi

        persistence:
          enabled: true
          storageClass: ebs
          accessModes:
            - ReadWriteOnce
          size: 8Gi

        nodeSelector: {}
        tolerations:
          - key: "karpenter"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "app"
            operator: "Equal"
            value: "opensearch"
            effect: "NoSchedule"

        labels:
          app: opensearch

        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app: opensearch
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app: opensearch

        antiAffinityTopologyKey: kubernetes.io/hostname
        antiAffinity: hard
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: karpenter
                    operator: In
                    values:
                      - enabled
                  - key: app
                    operator: In
                    values:
                      - opensearch

        ingress:
          enabled: true
          ingressClassName: nginx-external
          hosts:
            - opensearch<path:/eks/cluster/main/ingress#external_domain#AWSCURRENT>
          path: /
          tls: []

        extraObjects:
          - apiVersion: karpenter.sh/v1alpha5
            kind: Provisioner
            metadata:
              labels:
                app: opensearch
              name: opensearch
            spec:
              ttlSecondsAfterEmpty: 30
              ttlSecondsUntilExpired: 2592000
              labels:
                karpenter: enabled
                app: opensearch
              taints:
                - key: karpenter
                  value: enabled
                  effect: NoSchedule
              providerRef:
                name: al2-default
              requirements:
              - key: karpenter.k8s.aws/instance-category
                operator: In
                values:
                  - r
              - key: karpenter.k8s.aws/instance-memory
                operator: In
                values:
                - "16384"
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                - spot
                - on-demand
