apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=true,Delete=true
  name: loki
spec:
  weight: 100
  limits:
    cpu: 16
    memory: 128Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
  template:
    metadata:
      labels:
        role: loki
        karpenter: enabled
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: al2023-default
      requirements:
        - { key: karpenter.k8s.aws/instance-category, operator: In, values: [ t ]            }
        - { key: kubernetes.io/arch,                  operator: In, values: [ arm64, amd64 ] }
        - { key: kubernetes.io/os,                    operator: In, values: [ linux ]        }
        - { key: karpenter.sh/capacity-type,          operator: In, values: [ spot ]         }
      taints:
        - key: karpenter.sh/enabled
          value: 'true'
          effect: NoSchedule
