apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Wave 0
  - argo-cd

  # Wave 1
  - prometheus-stack
  
  # Wave 4 - depends on ingress/alb, prom/serviceMonitor, EBS CSI driver
  - opensearch
