apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Wave 0 - creates basic CRDs
  - karpenter # Used by other workloads to provision nodes
  - cluster-autoscaler
  - aws-load-balancer-controller
  - aws-ebs-csi-driver
  - external-dns
  - metrics-server
  - argocd-apps

  # Wave 1 - depends on karpenter provisioners and node templates
  - prometheus-stack # Creates ServiceMonitor, PodMonitor, ... used by other workloads
  #- ingress/nginx/external

  # Wave 3
  - argo-cd

  # Wave 4 - depends on ingress/alb, prom/serviceMonitor, EBS CSI driver
  - opensearch
