apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: system
  destination:
    namespace: cloud-controllers
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - group: '*'
    kind: ConfigMap
    name: aws-load-balancer-controller-leader
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.6.2
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: <path:/eks/cluster/main/details#name#AWSCURRENT>
        region: <path:/eks/cluster/main/details#region#AWSCURRENT>
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: <path:/eks/cluster/main/iam/roles#aws_load_balancer_controller#AWSCURRENT>
        defaultTags:
          cluster: <path:/eks/cluster/main/details#name#AWSCURRENT>
          created-by: aws-load-balancer-controller
        controllerConfig:
          # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/deploy/configurations/#feature-gates
          featureGates: {}
