apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: dev

bases:
  - ../../../base/infra/projects
  - ../../../base/infra/applications

patchesStrategicMerge: []
  #- overrides/argo-cd.yaml
