apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../../base/infra/projects
- ../../../base/infra/applications
- ../../../base/services/projects
- ../../../base/services/applications

labels:
- includeSelectors: true
  pairs:
    environment: dev

patches:
- path: overrides/bitnami-nginx.yaml
