apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: system
  destination:
    namespace: cloud-controllers
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: rue
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  source:
    chart: aws-ebs-csi-driver 
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    targetRevision: 2.25.0
    helm:
      releaseName: aws-ebs-csi-driver 
      values: |
        {
            "clusterName": <path:/eks/cluster/main/data-2/details#name#AWSCURRENT>,
            "region": <path:/eks/cluster/main/data-2/details#region#AWSCURRENT>,
            "serviceAccount": {
                "create": True,
                "annotations": {
                    "eks.amazonaws.com/role-arn": <path:/eks/cluster/main/data-2/iam/roles#aws_load_balancer_controller#AWSCURRENT>,
                }
            },
        }
