apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

openapi:
  # Reference: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json
  # Modified "io.argoproj.argocd.v1alpha1.ApplicationSourcePlugin" by adding the merge keys,
  # so the 'env' fields can be merged. HELM_VALUES, HELM_VALUES_OVERRIDE are both available now 
  # in the final manifest. Without the merge key, only the override is available.
  path: argocd.application.schema.json
