apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.2.0
    plugin:
      env:
        - name: HELM_VALUES
          value: |-
            global:
              deploymentMode: SingleBinary
            singleBinary:
              replicas: 0
              autoscaling:
                enabled: false
                minReplicas: 1
                maxReplicas: 1
                targetCPUUtilizationPercentage: 80
                targetMemoryUtilizationPercentage: 90
            loki:
              commonConfig:
                replication_factor: 1
              configStorageType: ConfigMap
              auth_enabled: true
              storage:
                type: filesystem
              compactor: {}
              analytics: {}
              query_range: {}
              querier: {}
              ingester: {}
