apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=true,Delete=true
  name: cronjob
spec:
  consolidation:
    enabled: true
  labels:
    role: cronjob
  taints:
    - key: karpenter
      value: enabled
      effect: NoSchedule
  providerRef:
    name: bottlerocket-default
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
