kind: AppProject
apiVersion:  argoproj.io/v1alpha1
metadata:
  name: security
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Security applications project
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - argocd
  destinations:
    - namespace: security
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
    ignore:
    - kind: TargetGroupBinding
    - kind: ConfigMap
  roles: []
  #syncWindows:
  #  - kind: allow
  #    schedule: '10 1 * * *'
  #    duration: 1h
  #    applications:
  #      - 'prometheus-stack'
  #    manualSync: true
