apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Wave 0 - reserverd for projects

  # Wave 1 - creates basic CRDs
  # Prune disabled and resources finalizer unset
  #- pixie
  - aws-load-balancer-controller
  - karpenter
  - external-dns
  - aws-ebs-csi-driver
  - cluster-autoscaler
  - metrics-server
  # Prometheus contains the stack ( wave 2 ) and the CRDs ( wave 0 )
  - prometheus

  # Wave 2 - depends on karpenter provisioners and node templates
  #- karpenter/awsnodetemplates
  #- karpenter/provisioners
  #- prometheus # Creates ServiceMonitor, PodMonitor, ... used by other workloads
  - ingress/nginx/external

  # Wave 4 - depends on ingress/alb, prom/serviceMonitor, EBS CSI driver
  - argo-cd

  # Wave 5 - depends on ingress/alb, prom/serviceMonitor, EBS CSI driver
  #- opensearch
