apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Wave 0 - creates basic CRDs
  - aws-load-balancer-controller # Prune disabled
  - karpenter                    # Prune disabled
  - external-dns                 # Prune disabled
  - cluster-autoscaler
  - aws-ebs-csi-driver
  - metrics-server

  # Wave 1 - depends on karpenter provisioners and node templates
  - karpenter/awsnodetemplates
  - karpenter/provisioners
  #- prometheus-stack # Creates ServiceMonitor, PodMonitor, ... used by other workloads
  - ingress/nginx/external

  # Wave 3
  - argo-cd

  # Wave 4 - depends on ingress/alb, prom/serviceMonitor, EBS CSI driver
  - opensearch
