apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=true
  name: al2-default
spec:
  amiFamily: AL2023
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 20Gi
      volumeType: gp3
  instanceProfile: KarpenterNodeRole-main
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: <path:/eks/cluster/main/details#name#AWSCURRENT>
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: <path:/eks/cluster/main/details#name#AWSCURRENT>
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="//"

    --//
    Content-Type: application/node.eks.aws

    # Karpenter Generated NodeConfig
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      cluster:
        name: <path:/eks/cluster/main/details#name#AWSCURRENT>
        apiServerEndpoint: <path:/eks/cluster/main/details#endpoint#AWSCURRENT>
        certificateAuthority: <path:/eks/cluster/main/details#ca_data#AWSCURRENT>
        #cidr: 10.100.0.0/16
      kubelet:
        config:
          maxPods: 110
    --//--