apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=true
  name: bottlerocket-default
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 4Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      encrypted: true
      volumeSize: 20Gi
      volumeType: gp3
  instanceProfile: KarpenterNodeRole-main
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: <path:/eks/cluster/main/details#name#AWSCURRENT>
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: <path:/eks/cluster/main/details#name#AWSCURRENT>
  userData: |-
    [settings.kubernetes.eviction-hard]
    "memory.available" = "12%"
    "nodefs.available" = "10%"
    "nodefs.inodesFree" = "5%"
    [settings.kubernetes.eviction-soft]
    "memory.available" = "15%"
    "nodefs.available" = "12%"
    "nodefs.inodesFree" = "8%"