apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: system
  destination:
    namespace: cloud-controllers
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  source:
    chart: aws-ebs-csi-driver 
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    targetRevision: 2.25.0
    helm:
      releaseName: aws-ebs-csi-driver 
      values: |
        storageClasses:
          - name: ebs
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
            volumeBindingMode: WaitForFirstConsumer
            reclaimPolicy: Delete
            allowVolumeExpansion: true
            parameters:
              encrypted: "true"
        controller:
          podLabels: {}
          replicaCount: 2
          resources: {}
          volumeModificationFeature:
            enabled: true
          defaultFsType: ext4
          serviceAccount:
            create: true
            annotations:
              eks.amazonaws.com/role-arn: <path:/eks/cluster/2023112620/main/iam/roles#ebs_csi_driver#AWSCURRENT>
