apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  labels: {}
  name: ingress
spec:
  consolidation:
    enabled: true
  labels:
    app: ingress
    karpenter: enabled
  taints:
    - key: karpenter
      value: enabled
      effect: NoSchedule
  providerRef:
    name: al2-max-conntrack
  requirements:
    - { key: karpenter.k8s.aws/instance-category, operator: In, values: [ t ]     }
    - { key: kubernetes.io/arch,                  operator: In, values: [ arm64 ] }
    - { key: kubernetes.io/os,                    operator: In, values: [ linux ] }
    - { key: karpenter.sh/capacity-type,          operator: In, values: [ spot ]  }
