apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=true
  name: prometheus
spec:
  consolidation:
    enabled: true
  labels:
    role: cronjob
  providerRef:
    name: bottlerocket-default
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
