apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: system
  destination:
    namespace: cloud-controllers
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: v0.32.1
    path: '' 
    helm:
      releaseName: karpenter
      values: |
        {
            "autoDiscovery": {
                "clusterName": <path:/eks/cluster/main/data-2/details#name#AWSCURRENT>,
            },
            "awsRegion": <path:/eks/cluster/main/data-2/details#region#AWSCURRENT>,
            "rbac": {
                "create": True,
                "serviceAccount": {
                    "create": True,
                    "annotations": {
                        "eks.amazonaws.com/role-arn": <path:/eks/cluster/main/data-2/iam/roles#karpenter#AWSCURRENT>,
                    }
                },
            },
            "extraArgs": {
                "balance-similar-node-groups": True,
                "skip-nodes-with-system-pods": False,
            },
        },
